services:
  wallabag:
    image: wallabag/wallabag:${VERSION}
    container_name: wallabag
    hostname: wallabag
    env_file: .env
    volumes:
      - images:/var/www/wallabag/web/assets/images
      - data:/var/www/wallabag/data
    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
    restart: always

volumes:
  data:
  images:

networks:
  default:
    name: $PROXY_NETWORK
    external: true
