services:
  wg-easy:
    image: weejewel/wg-easy:${VERSION}
    container_name: wg-easy
    hostname: wg-easy
    env_file: .env
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "${WG_PORT}:${WG_PORT}/udp"
      - "${WG_WEBUI_PORT}:${WG_WEBUI_PORT}/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2

networks:
  wg-easy:
    ipam:
      config:
        - subnet: 10.8.1.0/24
