services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:${VERSION}
    container_name: audiobookshelf
    hostname: audiobookshelf
    user: ${UID}:${GID}
    env_file: .env
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
    volumes:
      - ${AUDIOBOOKS_PATH}:/home/node/audiobooks
      - ${PODCASTS_PATH}:/home/node/podcasts
      - $PWD/config:/config
      - $PWD/metadata:/metadata

networks:
  default:
    name: $PROXY_NETWORK
    external: true