services:
  vaultwarden:
    image: vaultwarden/server:${VERSION}
    container_name: vaultwarden
    hostname: vaulwarden
    user: ${UID}:${GID}
    env_file: .env
    volumes:
      - ${DOCKER_STORAGE_PATH}/vaultwarden/data:/data
    ports:
      - "${PORT}:${PORT}"

    restart: always
    secrets:
      - vaultwarden_admin_token

secrets:
  vaultwarden_admin_token:
    file: admin_token.txt

networks:
  default:
    name: $PROXY_NETWORK
    external: true
