# Clone https://github.com/chriscrowe/docker-pihole-unbound and replace one-container/docker-compose.yaml

# Import network to work with VPN
include:
  - <path_to_wg-easy_docker-compose.yml>

volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:

services:
  pihole:
    container_name: pihole-unbound
    image: cbcrowe/pihole-unbound:${PIHOLE_VERSION}
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    env_file: .env
    ports:
      - 53:53/tcp
      - 53:53/udp
      - ${PIHOLE_WEBPORT:-80}:80/tcp
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    restart: unless-stopped
    # Required to work with VPN
    networks:
      wg-easy:
        ipv4_address: 10.8.1.3
    secrets:
      - pihole_ui_password

secrets:
  pihole_ui_password:
    file: ./pihole_ui_password.txt
