services:

  transmission:
    image: "linuxserver/transmission:${VERSION}"
    container_name: transmission
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DOWNLOAD_PATH}:/downloads
#      - ${MEDIA_PATH}:/media
    restart: unless-stopped
    ports:
      - 9091:9091
      - 51413:51413
    deploy:
      resources:
        limits:
          # cpus: '0.001'
          memory: 500M
