services:
  db:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file: db.env
    secrets:
      - postgres_password

  redis:
    env_file: db.env
    image: redis:x.x.x
# Does not take variable from env_file
#    image: "redis:${REDIS_VERSION}"
    container_name: redis
    hostname: nextcloud-redis
    restart: unless-stopped

  app:
    env_file: db.env
    image: nextcloud:x.x.x
    container_name: nextcloud
    # hostname: nextcloud
    hostname: ${NEXTCLOUD_SUBDOMAIN}.${MAIN_DOMAIN}
    restart: always
    ports:
      - ${NEXTCLOUD_PORT}:80
    volumes:
      - ${HOME}/nextcloud:/var/www/html
    depends_on:
      - db
      - redis
    secrets:
      - postgres_password

volumes:
  db:
  nextcloud:

networks:
  default:
    name: $PROXY_NETWORK
    external: true

secrets:
  postgres_password:
    file: ./postgres_nextcloud_password.txt
