services:
  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    restart: unless-stopped
    ports:
      - 8001:8000
    volumes:
      - yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env

volumes:
  yacht:
