services:
  jellyfin:
    image: "jellyfin/jellyfin:${VERSION}"
    container_name: jellyfin
    hostname: jellyfin
    user: ${UID}:${GID}
    volumes:
      - ${HOME}/boilerplates/jellyfin/config:/config
      - ${HOME}/Storage/Movies:/movies:readonly
      - ${HOME}/Storage/Series:/series:readonly
      - ${HOME}/.cache/jellyfin:/cache
    restart: always

networks:
  default:
    name: $PROXY_NETWORK
    external: true
