services:
  jellyfin:
    image: "jellyfin/jellyfin:${VERSION}"
    container_name: jellyfin
    hostname: jellyfin
    volumes:
      - ${HOME}/service-configs/jellyfin/config:/config
      - ${HOME}/usb_drive/media:/media:readonly
      - ${HOME}/.cache/jellyfin:/cache
    restart: 'unless-stopped'

networks:
  default:
    name: $PROXY_NETWORK
    external: true
